// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/balance_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vyacheslavskl/go-musthave-diploma-tpl/internal/models"
)

// MockBalanceServicer is a mock of BalanceServicer interface.
type MockBalanceServicer struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServicerMockRecorder
}

// MockBalanceServicerMockRecorder is the mock recorder for MockBalanceServicer.
type MockBalanceServicerMockRecorder struct {
	mock *MockBalanceServicer
}

// NewMockBalanceServicer creates a new mock instance.
func NewMockBalanceServicer(ctrl *gomock.Controller) *MockBalanceServicer {
	mock := &MockBalanceServicer{ctrl: ctrl}
	mock.recorder = &MockBalanceServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceServicer) EXPECT() *MockBalanceServicerMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceServicer) GetBalance(ctx context.Context, userID string) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceServicerMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceServicer)(nil).GetBalance), ctx, userID)
}

// GetWithdrawals mocks base method.
func (m *MockBalanceServicer) GetWithdrawals(ctx context.Context, userID string) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockBalanceServicerMockRecorder) GetWithdrawals(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockBalanceServicer)(nil).GetWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockBalanceServicer) Withdraw(ctx context.Context, userID string, req models.WithdrawRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceServicerMockRecorder) Withdraw(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceServicer)(nil).Withdraw), ctx, userID, req)
}
