// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/order_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vyacheslavskl/go-musthave-diploma-tpl/internal/models"
)

// MockOrderServicer is a mock of OrderServicer interface.
type MockOrderServicer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServicerMockRecorder
}

// MockOrderServicerMockRecorder is the mock recorder for MockOrderServicer.
type MockOrderServicerMockRecorder struct {
	mock *MockOrderServicer
}

// NewMockOrderServicer creates a new mock instance.
func NewMockOrderServicer(ctrl *gomock.Controller) *MockOrderServicer {
	mock := &MockOrderServicer{ctrl: ctrl}
	mock.recorder = &MockOrderServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServicer) EXPECT() *MockOrderServicerMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockOrderServicer) AddOrder(ctx context.Context, userID, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockOrderServicerMockRecorder) AddOrder(ctx, userID, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockOrderServicer)(nil).AddOrder), ctx, userID, number)
}

// GetOrders mocks base method.
func (m *MockOrderServicer) GetOrders(ctx context.Context, userID string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderServicerMockRecorder) GetOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderServicer)(nil).GetOrders), ctx, userID)
}
